# Generated by Django 4.1.4 on 2022-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_delete_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("Layoffs", "Layoffs"),
                    ("Hiring freeze", "Hiring Freeze"),
                    ("Hiring", "Hiring"),
                ],
                default="Hiring",
                max_length=14,
            ),
        ),
    ]
